AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SnappedNetLambdaTest

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 2048

Resources:
  SnappedNetLambdaTestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      FunctionName: SnappedNetLambdaTest
      Handler: SnappedNetLambdaTest::SnappedNetLambdaTest.Function::FunctionHandler
      Runtime: dotnet8
      #Runtime: java21
      # SnapStart:
      #   ApplyOn: PublishedVersions
      Architectures:
      - x86_64
      MemorySize: 2048
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          FAKE: FAKE
          # AWS_LAMBDA_EXEC_WRAPPER: /opt/snapper4net_wrapper.sh
      AutoPublishAlias: live
    # see https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-custom-runtimes.html
    # we need to use makefile to have an ability to switch between runtimes (dotnet8 vs java21) for testing purposes.
    Metadata:
      BuildMethod: makefile
Outputs:
  SnappedNetLambdaTestFunction:
    Description: Snapped Test Function ARN
    Value: !GetAtt SnappedNetLambdaTestFunction.Arn
